# -- Number of replicas (only applicable when autoscaling is not used)
replicaCount: 1

image:
  # -- Image Registry
  repository: customer-api
  # -- Image Pull Policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Specify a imagePullSecrets array
imagePullSecrets: []
# -- Override chart name
nameOverride: ""
# -- Override chart fullname
fullnameOverride: ""

# -- Map of pod annotations
podAnnotations: {}
# -- Map of pod labels
podLabels: {}

# -- Map of pod security context
podSecurityContext: {}

# -- Map of security context
securityContext: {}

service:
  # -- Kubernetes service type
  type: ClusterIP
  # -- Kubernetes service port
  port: 80

# -- Container port to expose
port: 8000

ingress:
  # -- Enable Ingress
  enabled: false
  # -- Ingress Class Name
  className: ""
  # -- Ingress Annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress TLS Configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Resource limits and requests
resources: {}

autoscaling:
  # -- Enable autoscaling for deployment
  enabled: false
  # -- Minimum number of pods to run
  minReplicas: 2
  # -- Maximum number of pods to run
  maxReplicas: 10
  # -- Target CPU utilization percentage
  targetCPUUtilizationPercentage: 80
  # -- Target memory utilization percentage
  # targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  # -- Enable PodDisruptionBudget
  enabled: false
  # -- Minimum available pods
  minAvailable: 1

# -- Environment variables to set in the main container.
envVars: {}

# -- Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

## - Node selector for pod assignment
nodeSelector: {}

## - Tolerations for pod assignment
tolerations: []

## - Affinity for pod assignment
affinity: {}
